### ISSUE TITLE
The breeze of OOP

### ISSUE THREAD

**Issue by szepeviktor** [wearerequired/wp-requirements-check#10]
Hello 👋! I'm experimenting with an OOP-only solution for requirements checking.

```php
    (new Requirements())
        ->php('7.4')
        ->wp('4.9')
        ->multisite(false)
        ->plugins(['polylang/polylang.php'])
        ->packages(['psr/container', 'psr/log-implementation'])
        ->passes() // Returns a boolean.
```

Implementing here https://github.com/szepeviktor/small-project/blob/master/src/Requirements.php

Are you interested?

**Comment by szepeviktor** [comment]
All this comes from a theoretical research https://github.com/szepeviktor/small-project/issues/6
"The Ultimate WordPress Plugin Main File"

**Comment by cliffordp** [comment]
@szepeviktor sounds like a similar task over on mine. For your reference: https://github.com/cliffordp/cliff-wp-plugin-boilerplate/issues/72

**Comment by szepeviktor** [comment]
Thank you for your reply :)

I'm talking about OOP here. Both your current solution and `micropackage/requirements` uses an array which to me is an "I-just-hold-data" container, not a self-aware object.

With `Requirements` and `Config` I try **to break out** of WordPressy thinking, out of "PHP4-like" code.
https://github.com/szepeviktor/small-project/tree/master/src

**Comment by szepeviktor** [comment]
Closing it as a duplicate.
