### ISSUE TITLE
add support to check plugin version

### ISSUE THREAD

**Issue by luizbills** [wearerequired/wp-requirements-check#4]
```php
$requirements_check = new WP_Requirements_Check( array(
	'title' => 'My awesome plugin',
	'php'   => '7.0',
	'woocommerce' => '3.2' // plugin slug as key
) );
```

**Comment by swissspidy** [comment]
Hey there

Thanks for your suggestion!

We could probably do something like this:

```
$requirements_check = new WP_Requirements_Check( array(
	'title' => 'My awesome plugin',
	'php'   => '7.0',
	'plugins' => [
		'woocommerce/woocommerce.php' => '3.2'
	],
) );
```

We'd probably enter [TGMPA](https://github.com/TGMPA/TGM-Plugin-Activation) territory by doing this, so we'd have to draw a clear line on what should go into this library and what not.

**Comment by luizbills** [comment]
Sorry for the delay.

But does TGMPA prevents activation of the plugin/theme or just warns you that you need to install some dependencies?

**Comment by swissspidy** [comment]
According to the [documentation](http://tgmpluginactivation.com/configuration/) it supports both.
